	name: Il2CppInspectorRedux Build
 on:
  push:
    branches: [ master ]
 
  workflow_dispatch:
 jobs:
  build:
    runs-on: windows-latest
 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
 
      - uses: microsoft/setup-msbuild@v1.1
 
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
              ${{ runner.os }}-nuget-
 
      - name: Restore NuGet packages
        run: nuget restore
      
      - name: Build GUI
        run: msbuild /t:Il2CppInspector_GUI:publish /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFramework=net8.0-windows /p:SelfContained=false /verbosity:minimal
 
      - name: Build CLI
        run: msbuild /t:Il2CppInspector_CLI:publish /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFramework=net8.0 /p:SelfContained=false /verbosity:minimal
 
      - name: Add Plugins folder (GUI)
        shell: pwsh
        working-directory: Il2CppInspector.GUI/bin/Release/net8.0-windows/win-x64/publish
        run: ../../../../../../get-plugins.ps1
 
      - name: Add Plugins folder (CLI)
        shell: pwsh
        working-directory: Il2CppInspector.CLI/bin/Release/net8.0/win-x64/publish
        run: ../../../../../../get-plugins.ps1
 
      - name: Upload GUI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Il2CppInspectorRedux.GUI
          path: Il2CppInspector.GUI/bin/Release/net8.0-windows/win-x64/publish
 
      - name: Upload CLI Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Il2CppInspectorRedux.CLI
          path: Il2CppInspector.CLI/bin/Release/net8.0/win-x64/publish
